const Data = {
  message: "Getting data Successful.",
  data: [
    {
      id: 3,
      0: 3,
      title: "yirila",
      1: "yirila",
      artiste_id: "lil zed",
      2: "lil zed",
      year: "2022",
      3: "2022",
      url: "/uploads/Lil Zed _Yirila (clip officiel 2022).mp3",
      4: "/uploads/Lil Zed _Yirila (clip officiel 2022).mp3",
      image: "/uploads/lil_zed.jpg",
      5: "/uploads/lil_zed.jpg",
      duration: "3",
      6: "3",
      created_at: "0",
      7: "0",
      created_by: 0,
      8: 0,
      updated_at: "6",
      9: "6",
      updated_by: 2,
      10: 2,
      album_name: "Destin",
      11: "Destin",
      country: null,
      12: null,
      genre: 'rap',
      13: 'rap'
    },
    {
      id: 7,
      0: 7,
      title: "Yirila",
      1: "Yirila",
      artiste_id: "lil zed",
      2: "lil zed",
      year: "2022",
      3: "2022",
      url: "/uploads/Lil Zed _Yirila (clip officiel 2022).mp3",
      4: "/uploads/Lil Zed _Yirila (clip officiel 2022).mp3",
      image: "/uploads/lil_zed.jpg",
      5: "/uploads/lil_zed.jpg",
      duration: "3",
      6: "3",
      created_at: "0",
      7: "0",
      created_by: 0,
      8: 0,
      updated_at: "0",
      9: "0",
      updated_by: 0,
      10: 0,
      album_name: "",
      11: "",
      country: "ML",
      12: "ML",
      genre: 'rap',
      13: 'rap'
    },
    {
      id: 8,
      0: 8,
      title: "Diarabi",
      1: "Diarabi",
      artiste_id: "Malakey",
      2: "Malakey",
      year: "2022",
      3: "2022",
      url: "/uploads/Malakey - Diarabi (Clip Officiel).mp3",
      4: "/uploads/Malakey - Diarabi (Clip Officiel).mp3",
      image: "/uploads/malakey.png",
      5: "/uploads/malakey.png",
      duration: "3:00",
      6: "3:00",
      created_at: "0",
      7: "0",
      created_by: 0,
      8: 0,
      updated_at: "0",
      9: "0",
      updated_by: 0,
      10: 0,
      album_name: "",
      11: "",
      country: "ML",
      12: "ML",
      genre: 'pop',
      13: 'pop'
    },
    {
      id: 9,
      0: 9,
      title: "Yirila",
      1: "Yirila",
      artiste_id: "lil zed",
      2: "lil zed",
      year: "2022",
      3: "2022",
      url: "/uploads/Lil Zed _Yirila (clip officiel 2022).mp3",
      4: "/uploads/Lil Zed _Yirila (clip officiel 2022).mp3",
      image: "/uploads/lil_zed.jpg",
      5: "/uploads/lil_zed.jpg",
      duration: "3",
      6: "3",
      created_at: "0",
      7: "0",
      created_by: 0,
      8: 0,
      updated_at: "0",
      9: "0",
      updated_by: 0,
      10: 0,
      album_name: "Destin",
      11: "Destin",
      country: null,
      12: null,
      genre: 'rap',
      13: 'rap'
    },
  ],
};


export default Data;